-- Table pour les précommandes ORADIA - Version Production
-- À exécuter dans le dashboard Supabase > SQL Editor

-- Table principale des précommandes
CREATE TABLE IF NOT EXISTS preorders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stripe_session_id TEXT UNIQUE NOT NULL,
    payment_intent_id TEXT,
    stripe_event_id TEXT, -- Pour debug/idempotence avancée
    customer_id TEXT, -- ID client Stripe si disponible
    email TEXT NOT NULL,
    offer TEXT NOT NULL CHECK (offer IN ('standard', 'tirage-offert', 'edition-signature')),
    amount_total INTEGER NOT NULL,
    currency TEXT NOT NULL DEFAULT 'eur',
    full_name TEXT,
    shipping_address TEXT,
    postal_code TEXT,
    city TEXT,
    paid_status TEXT DEFAULT 'pending' CHECK (paid_status IN ('pending', 'completed', 'failed', 'cancelled')),
    source TEXT DEFAULT 'oradia-precommande',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    checkout_completed_at TIMESTAMP WITH TIME ZONE -- Quand le webhook est reçu
);

-- Index pour optimiser les requêtes critiques
CREATE INDEX IF NOT EXISTS idx_preorders_stripe_session_id ON preorders(stripe_session_id);
CREATE INDEX IF NOT EXISTS idx_preorders_payment_intent_id ON preorders(payment_intent_id);
CREATE INDEX IF NOT EXISTS idx_preorders_paid_status ON preorders(paid_status);
CREATE INDEX IF NOT EXISTS idx_preorders_email ON preorders(email);
CREATE INDEX IF NOT EXISTS idx_preorders_created_at ON preorders(created_at);
CREATE INDEX IF NOT EXISTS idx_preorders_checkout_completed_at ON preorders(checkout_completed_at);

-- Trigger pour mettre à jour updated_at automatiquement
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_preorders_updated_at 
    BEFORE UPDATE ON preorders 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Trigger pour mettre à jour checkout_completed_at
CREATE OR REPLACE FUNCTION set_checkout_completed_at()
RETURNS TRIGGER AS $$
BEGIN
    -- Mettre à jour checkout_completed_at uniquement quand paid_status passe à 'completed'
    IF OLD.paid_status != 'completed' AND NEW.paid_status = 'completed' THEN
        NEW.checkout_completed_at = NOW();
    END IF;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER set_checkout_completed_at_trigger
    BEFORE UPDATE ON preorders
    FOR EACH ROW
    EXECUTE FUNCTION set_checkout_completed_at();

-- RLS (Row Level Security) - Sécurité optimale
ALTER TABLE preorders ENABLE ROW LEVEL SECURITY;

-- Politique pour permettre les opérations depuis le service role uniquement
CREATE POLICY "Service role full access to preorders" ON preorders
    FOR ALL USING (auth.role() = 'service_role');

-- Fonction pour compter les précommandes payées (optimisée)
CREATE OR REPLACE FUNCTION count_paid_preorders()
RETURNS INTEGER AS $$
BEGIN
    RETURN (
        SELECT COUNT(*) 
        FROM preorders 
        WHERE paid_status = 'completed'
    );
END;
$$ LANGUAGE plpgsql;

-- Fonction pour obtenir les statistiques de progression
CREATE OR REPLACE FUNCTION get_preorder_stats()
RETURNS TABLE (
    goal INTEGER,
    sold INTEGER,
    remaining INTEGER,
    percent INTEGER
) AS $$
DECLARE
    goal_val INTEGER := 500; -- Objectif fixe
    sold_val INTEGER;
BEGIN
    SELECT COUNT(*) INTO sold_val
    FROM preorders 
    WHERE paid_status = 'completed';
    
    RETURN QUERY SELECT 
        goal_val,
        sold_val,
        GREATEST(goal_val - sold_val, 0),
        LEAST(ROUND((sold_val::FLOAT / goal_val::FLOAT) * 100), 100);
END;
$$ LANGUAGE plpgsql;

-- Vue pour monitoring facile
CREATE OR REPLACE VIEW preorder_summary AS
SELECT 
    COUNT(*) as total_orders,
    COUNT(*) FILTER (WHERE paid_status = 'completed') as completed_orders,
    COUNT(*) FILTER (WHERE paid_status = 'pending') as pending_orders,
    SUM(amount_total) FILTER (WHERE paid_status = 'completed') as total_revenue,
    ROUND(AVG(amount_total) FILTER (WHERE paid_status = 'completed')) as avg_order_value
FROM preorders;

-- Commentaires pour documentation
COMMENT ON TABLE preorders IS 'Table des précommandes ORADIA avec tracking Stripe';
COMMENT ON COLUMN preorders.stripe_session_id IS 'ID unique de session Stripe - clé d idempotence';
COMMENT ON COLUMN preorders.payment_intent_id IS 'ID du paiement Stripe';
COMMENT ON COLUMN preorders.stripe_event_id IS 'ID de l événement Stripe pour debug';
COMMENT ON COLUMN preorders.paid_status IS 'pending = session créée, completed = paiement confirmé';
COMMENT ON COLUMN preorders.checkout_completed_at IS 'Horodatage de la confirmation de paiement';
