// scripts/_mirror-pairs.js
// Table des cartes miroir (paires opposées), partagée par
// generate-card-pages.js (FR) et generate-card-pages-en.js (EN).
// Clés/valeurs en noms français (clé canonique du deck) ; la famille
// Mémoire Cosmos n'a pas de miroir (10 cartes).
module.exports = {
  // Émotions
  'JOIE': 'TRISTESSE', 'TRISTESSE': 'JOIE',
  'AMOUR': 'SOLITUDE', 'SOLITUDE': 'AMOUR',
  'ÉMERVEILLEMENT': 'DÉGOÛT', 'DÉGOÛT': 'ÉMERVEILLEMENT',
  'SÉRÉNITÉ': 'CONFUSION', 'CONFUSION': 'SÉRÉNITÉ',
  'COLÈRE': 'IMPUISSANCE', 'IMPUISSANCE': 'COLÈRE',
  'COURAGE': 'PEUR', 'PEUR': 'COURAGE',
  'CONFIANCE': 'HONTE', 'HONTE': 'CONFIANCE',
  'FIERTÉ': 'CULPABILITÉ', 'CULPABILITÉ': 'FIERTÉ',
  'IMPATIENCE': 'PATIENCE', 'PATIENCE': 'IMPATIENCE',
  // Besoins
  'RECONNAISSANCE': 'SÉCURITÉ', 'SÉCURITÉ': 'RECONNAISSANCE',
  'LIBERTÉ': 'SOUTIEN', 'SOUTIEN': 'LIBERTÉ',
  'REPOS': 'CLARTÉ', 'CLARTÉ': 'REPOS',
  'APPARTENANCE': 'AUTONOMIE', 'AUTONOMIE': 'APPARTENANCE',
  'STIMULATION': 'HARMONIE', 'HARMONIE': 'STIMULATION',
  'AMOUR REÇU': 'LE SENS', 'LE SENS': 'AMOUR REÇU',
  'PROTECTION': 'EXPANSION', 'EXPANSION': 'PROTECTION',
  'INTIMITÉ': 'CRÉATIVITÉ', 'CRÉATIVITÉ': 'INTIMITÉ',
  'AUTHENTICITÉ': 'GUIDANCE', 'GUIDANCE': 'AUTHENTICITÉ',
  // Transmutation
  'ACCEPTATION': 'TRANSFORMATION', 'TRANSFORMATION': 'ACCEPTATION',
  'LÂCHER-PRISE': 'LIBÉRATION', 'LIBÉRATION': 'LÂCHER-PRISE',
  'PARDON': 'ALIGNEMENT', 'ALIGNEMENT': 'PARDON',
  'DÉTACHEMENT': 'PURIFICATION', 'PURIFICATION': 'DÉTACHEMENT',
  'ANCRAGE': 'OUVERTURE', 'OUVERTURE': 'ANCRAGE',
  'FLUIDITÉ': 'CLARIFICATION', 'CLARIFICATION': 'FLUIDITÉ',
  'PRISON MENTALE': 'ESPRIT LIBRE', 'ESPRIT LIBRE': 'PRISON MENTALE',
  'VIDE': 'PLÉNITUDE', 'PLÉNITUDE': 'VIDE',
  'INCARNATION': 'TRANSCENDANCE', 'TRANSCENDANCE': 'INCARNATION',
  // Archétypes
  'LE SAGE': 'LE GUERRIER', 'LE GUERRIER': 'LE SAGE',
  'LA PRÊTRESSE': 'LE BÂTISSEUR', 'LE BÂTISSEUR': 'LA PRÊTRESSE',
  'LE RÊVEUR': 'LE VISIONNAIRE', 'LE VISIONNAIRE': 'LE RÊVEUR',
  "L'ENFANT": 'LE VOYAGEUR', 'LE VOYAGEUR': "L'ENFANT",
  'LE MAGE': 'LE PASSEUR', 'LE PASSEUR': 'LE MAGE',
  'LE VEILLEUR': 'LE PORTEUR', 'LE PORTEUR': 'LE VEILLEUR',
  'LE NOMADE': 'LA TISSEUSE', 'LA TISSEUSE': 'LE NOMADE',
  "L'ALCHIMISTE": 'LE JUSTE', 'LE JUSTE': "L'ALCHIMISTE",
  "L'OBSERVATEUR": "L'INITIATEUR", "L'INITIATEUR": "L'OBSERVATEUR",
  // Révélations
  'CLÉ': 'PORTE', 'PORTE': 'CLÉ',
  'MESSAGE': 'SYNCHRONICITÉ', 'SYNCHRONICITÉ': 'MESSAGE',
  'SIGNE': 'VISION', 'VISION': 'SIGNE',
  'PRÉSAGE': 'ÉVEIL', 'ÉVEIL': 'PRÉSAGE',
  'LUMIÈRE': 'DÉVOILEMENT', 'DÉVOILEMENT': 'LUMIÈRE',
  'VÉRITÉ': 'ILLUSION', 'ILLUSION': 'VÉRITÉ',
  'ÉTINCELLE': 'SILENCE', 'SILENCE': 'ÉTINCELLE',
  'CHIFFRE': 'SYMBOLE', 'SYMBOLE': 'CHIFFRE',
  'ORIGINE': 'DESTIN', 'DESTIN': 'ORIGINE',
  // Actions
  'AGIR': 'ÉCOUTER', 'ÉCOUTER': 'AGIR',
  'DIRE': 'RECEVOIR', 'RECEVOIR': 'DIRE',
  'CRÉER': 'ACCUEILLIR', 'ACCUEILLIR': 'CRÉER',
  'PARTAGER': 'PROTÉGER', 'PROTÉGER': 'PARTAGER',
  'ALLER VERS': 'SE RETIRER', 'SE RETIRER': 'ALLER VERS',
  'CHOISIR': 'PATIENTER', 'PATIENTER': 'CHOISIR',
  'EXPRIMER': 'OBSERVER', 'OBSERVER': 'EXPRIMER',
  'ORDONNER': 'RÉCONCILIER', 'RÉCONCILIER': 'ORDONNER',
  'MANIFESTER': 'ARRÊTER', 'ARRÊTER': 'MANIFESTER'
};
