name: Sync from Hugging Face Space

on:
  repository_dispatch:
    types: [hf-space-updated]
  workflow_dispatch:
    inputs:
      hf_space_id:
        description: "HF Space ID (org/space)"
        required: false
      hf_space_branch:
        description: "Branche du Space"
        required: false
        default: "main"

permissions:
  contents: write

concurrency:
  group: sync-from-hf
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1) Repo GitHub
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false

      # 2) Outils
      - name: Install git-lfs, rsync, jq
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y git-lfs rsync jq
          git lfs install

      # 3) Résolution des variables (branche/space)
      - name: Resolve config (branch & Space)
        id: cfg
        run: |
          set -euxo pipefail
          # Branche cible
          BRANCH="${GITHUB_REF_NAME:-}"
          if [ -z "$BRANCH" ]; then
            BRANCH="$(jq -r '.repository.default_branch // "main"' "$GITHUB_EVENT_PATH")"
          fi
          echo "branch=$BRANCH" >> "$GITHUB_OUTPUT"

          # Space ID (input > secret)
          SPACE_ID_INPUT="${{ github.event.inputs.hf_space_id }}"
          SPACE_ID_SECRET="${{ secrets.HF_SPACE_ID }}"
          SPACE_ID="${SPACE_ID_INPUT:-$SPACE_ID_SECRET}"
          if [ -z "$SPACE_ID" ]; then
            echo "::error::HF_SPACE_ID manquant (input ou secret)."
            exit 1
          fi
          echo "space_id=$SPACE_ID" >> "$GITHUB_OUTPUT"

          # Space branch (input > secret > main)
          SPACE_BRANCH_INPUT="${{ github.event.inputs.hf_space_branch }}"
          SPACE_BRANCH_SECRET="${{ secrets.HF_SPACE_BRANCH }}"
          SPACE_BRANCH="${SPACE_BRANCH_INPUT:-${SPACE_BRANCH_SECRET:-main}}"
          echo "space_branch=$SPACE_BRANCH" >> "$GITHUB_OUTPUT"

      # 4) Clone HF (token dans l'URL pour éviter tout prompt)
      - name: Clone HF Space (token-in-URL, masked)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          set -euo pipefail
          CLONE_DIR="$RUNNER_TEMP/hfspace"
          rm -rf "$CLONE_DIR"

          if [ -n "${HF_TOKEN:-}" ]; then
            # On coupe l’echo des commandes pour ne pas afficher l’URL
            set +x
            URL="https://__token__:${HF_TOKEN}@huggingface.co/spaces/${{ steps.cfg.outputs.space_id }}"
            git clone --branch "${{ steps.cfg.outputs.space_branch }}" "$URL" "$CLONE_DIR"
            set -x
          else
            # Space public : pas besoin de token
            git clone --branch "${{ steps.cfg.outputs.space_branch }}" \
              "https://huggingface.co/spaces/${{ steps.cfg.outputs.space_id }}" \
              "$CLONE_DIR"
          fi

      # 5) BONUS — matérialiser les fichiers LFS (vraies binaires)
      - name: Materialize LFS files from HF clone
        working-directory: ${{ runner.temp }}/hfspace
        run: |
          set -euxo pipefail
          git lfs install
          git lfs fetch --all || true
          git lfs checkout || true

      # 6) Miroir HF → GitHub (respecte .gitignore, supprime ce qui a été retiré côté HF)
      - name: Mirror files (HF → GitHub working tree)
        run: |
          set -euxo pipefail
          CLONE_DIR="$RUNNER_TEMP/hfspace"
          rsync -a --delete \
            --exclude '.git/' \
            --filter=':- .gitignore' \
            "$CLONE_DIR/" .

      # 7) Commit & push (HF gagne, pas de rebase ni conflits)
      - name: Commit & push (HF wins)
        run: |
          set -euxo pipefail
          BRANCH="${{ steps.cfg.outputs.branch }}"

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "No changes after sync. Exiting."
            exit 0
          fi

          # Neutraliser LFS côté commit (évite les pointeurs pour images web)
          git -c filter.lfs.clean= \
              -c filter.lfs.smudge= \
              -c filter.lfs.process= \
              -c filter.lfs.required=false add -A

          git -c filter.lfs.clean= \
              -c filter.lfs.smudge= \
              -c filter.lfs.process= \
              -c filter.lfs.required=false commit \
              -m "chore(sync): mirror HF Space → GitHub $(date -u +%F-%H%M%SZ)"

          git fetch origin "$BRANCH" || true
          if ! git ls-remote --exit-code --heads origin "$BRANCH" >/dev/null 2>&1; then
            git push --set-upstream origin "HEAD:$BRANCH"
          else
            git push --force-with-lease origin "HEAD:$BRANCH"
          fi
