name: Sync from Hugging Face Space

on:
  repository_dispatch:
    types: [hf-space-updated]
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}


permissions:
  contents: write

concurrency:
  group: sync-from-hf
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      HF_SPACE_ID: ${{ secrets.HF_SPACE_ID }}
      HF_SPACE_BRANCH: ${{ secrets.HF_SPACE_BRANCH || 'main' }}
      GIT_LFS_SKIP_SMUDGE: "1"   # ok pour le pull, n'affecte pas le clean
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-lfs & rsync
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y git-lfs rsync
          git lfs install --system
          git lfs version

      - name: Configure git user (CI)
        run: |
          git config user.name  "oradia-sync-bot"
          git config user.email "actions@users.noreply.github.com"

      - name: Clone HF Space to temp
        env:
          CLONE_DIR: ${{ runner.temp }}/hfspace
        run: |
          set -eux
          rm -rf "$CLONE_DIR"
          git clone --depth 1 --branch "${HF_SPACE_BRANCH:-main}" \
            "https://huggingface.co/spaces/${HF_SPACE_ID}" "$CLONE_DIR"

      - name: Sync files from HF Space -> repo (overwrite)
        env:
          CLONE_DIR: ${{ runner.temp }}/hfspace
        run: |
          set -eux
          rsync -av --delete \
            --exclude ".git/" \
            --exclude ".github/workflows/" \
            "$CLONE_DIR"/ ./
      - name: Untrack images from LFS (one-time migration)
        run: |
          set -eux
          # 1) retirer le tracking LFS des images
          git lfs untrack "*.png" "*.jpg" "*.jpeg" "*.webp" "*.gif" || true
          # 2) nettoyer .gitattributes
          sed -i '/\*.png filter=lfs/d; /\*.jpg filter=lfs/d; /\*.jpeg filter=lfs/d; /\*.gif filter=lfs/d; /\*.webp filter=lfs/d' .gitattributes || true
          git add .gitattributes || true

          # 3) exporte tous les fichiers LFS vers Git normal
          git lfs migrate export --include="*.png,*.jpg,*.jpeg,*.gif,*.webp" --everything

          # 4) commit + push (les images seront désormais des blobs git classiques)
          git add -A
          git commit -m "chore: remove LFS for images (exported)"
          git push


      - name: Commit changes
        run: |
          set -eux
          if ! git diff --cached --quiet || ! git diff --quiet; then
            git add -A
            git commit -m "chore(sync): overwrite from HF Space"
          fi

      # 🚀 Pousse d’abord les blobs LFS, puis la ref git
      - name: Push LFS objects
        run: |
          set -eux
          git lfs ls-files || true
          git lfs push --all origin HEAD

      - name: Push refs
        run: |
          set -eux
          git push

          else
            echo "No changes to commit."
          fi
