jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      HF_SPACE_ID: ${{ secrets.HF_SPACE_ID }}     # ex: username/my-space
      HF_SPACE_BRANCH: ${{ secrets.HF_SPACE_BRANCH || 'main' }}
      GIT_LFS_SKIP_SMUDGE: "1"
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-lfs & rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs rsync
          git lfs install

      - name: Configure git user (CI)
        run: |
          git config user.name  "oradia-sync-bot"
          git config user.email "actions@users.noreply.github.com"

      - name: Clone HF Space to temp
        env:
          CLONE_DIR: ${{ runner.temp }}/hfspace
        run: |
          set -eux
          rm -rf "$CLONE_DIR"
          git clone --depth 1 --branch "${HF_SPACE_BRANCH:-main}" \
            "https://huggingface.co/spaces/${HF_SPACE_ID}" "$CLONE_DIR"

      - name: Sync files from HF Space -> repo (one-way, overwrite)
        env:
          CLONE_DIR: ${{ runner.temp }}/hfspace
        run: |
          set -eux
          # On écrase le contenu du repo par celui du Space.
          # On protège le dossier workflow pour éviter l’auto-suppression.
          rsync -av --delete \
            --exclude ".git/" \
            --exclude ".github/workflows/" \
            "$CLONE_DIR"/ ./

      - name: Commit if changes
        run: |
          set -eux
          if ! git diff --quiet; then
            git add -A
            git commit -m "chore(sync): overwrite from HF Space"
            git push
          else
            echo "No changes to commit."
          fi
